# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 16:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 18, 10, 20, 904712)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to=main_app.models.user_directory_path, verbose_name='plik'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='właściciel'),
        ),
    ]
