# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170418_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 8, 30, 51, 90508, tzinfo=utc)),
        ),
    ]
