# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170419_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
