# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170420_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
