# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_documents_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
