# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='session',
        ),
        migrations.AddField(
            model_name='tokens',
            name='key',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='tokens',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
