# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20170515_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
